version: 1

formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: auto_sort.log
    when: D
    backupCount: 7

root:
  level: INFO
  handlers: [console, file]
  propagate: true
